export { default as Navbar } from "./Navbar";
export { default as Footer } from "./Footer";
export { default as VerticalSlider } from "./vertical slider/VerticalSlider";
export { default as Game } from "./game/Game";
export { default as SubNavbar } from "./SubNavbar";
export { default as Sidebar } from "./Sidebar";
export { default as IconSidebar } from "./IconSidebar";
export { default as Content } from "./Content";
export { default as CodeSnippets } from "./codeSnippets/CodeSnippets";
export { default as CodeSnippet } from "./codeSnippets/CodeSnippet";
